site_name: ZX's MkDocs
repo_url: https://gitee.com/rano-zink/mymkdocs/
repo_name: /mymkdocs/
edit_uri: ""
site_description: 能做一点是一点，能学一点是一点。

copyright: Copyright &copy; 2023 - 2024 zhaoxin

theme : readthedocs

nav: 
  - 主页: index.md
  - 主线:
      - 行波马达:  
        - SPI: project/行波马达/SPI.md
  - 支线: 
    - cpp: 
      -  基本语法: project/cpp/01demo.md
      - 重要概念:  project/cpp/CPPoutline.md
    - os : project/操作系统/OS.md




